title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dgenezini.github.io/docs-sample

aux_links:
  Template Repository: https://github.com/dgenezini/docs-sample
